### ISSUE TITLE
Documentation: how to tell daemon which media files & how clients can toggle audio

### ISSUE THREAD

**Issue by mozai** [wetfish/sync#12]
Could use more instructions, needed a human to tell me "it only looks in ./public/media/"

Should mention that is expects every file in ./public/media/ to be video files (had an *.m3u file in there, and it crashed the daemon).

Should mention is only scans the dir and gets media duration information at start-time.  I removed a file during runtime and it still sent the URL to that file to clients, and waited for that file's duration before prompting clients to fetch/play the next.  I also swapped out one of the files for another (re-using the filename), and it DID send the new data, but it prompted the clients to fetch/play the next file at the end of the original file, not at the end of the new file.

Should mention the webbrowser client can toggle mute-audio by pressing the Shift key.  (nice feature, useful)

Should mention webbrowsers usually don't play audio of autoplaying <video> elements, not without some mouse/keyboard interaction with the <video> element first.  HOWEVER, if I used the Shift key for the initial keyboard interaction, that would halt the <video> element and I don't know how to resume it without force-reloading the page.

Should mention the progress bar appears immediately on mouseover, but has an N-second delay to vanish on mouseout.

**Comment by itsrachelfish** [comment]
@mozai The readme has been updated with usage instructions. If you feel that some information is missing, feel free to create a pull request.
