### ISSUE TITLE
req: iterate N times then quit

### ISSUE THREAD

**Issue by mozai** [wetfish/sync#13]
When this daemon will be used for scheduled events, would be nice to say "present the media list once, then quit."  My particular use-case is N=2, but I could simulate that by having multiple links to the same file in ascii order.  (ie files named A,B,C,D,E,F,G where E links to B and F links to C).

I could have two cronjobs, one to start and a second hours later to pkill the first, but that'd require running ffprobe on every file and having to do the duration arithmetic on paper.  Would rather just say "do each file once then quit", or even better "do the folder N times then quit."

**Comment by mozai** [comment]
Tried running it with ye olde `childpid=$! ; sleep $TIMEOUT && kill $childpid; ` bash trick, but this doesn't work because `npm start` launches a child process `node server.js` that ignores the parent's death (SIGHUP), and processes don't see the pids of grandchildren unless the children say so via some ipc.  I'm going to use `pkill node` for now but that only works if I'm not running _any_ other Node.JS jobs/daemons, and only if I'm not allowed to kill other people's Node.JS jobs/daemons.

**Comment by itsrachelfish** [comment]
@mozai I think it would make sense if this was a configuration option. The value could be boolean or integer, which would change the behavior.

For example, `repeat=true` would repeat the playlist indefinitely. `repeat=false` would only play the playlist once.

`repeat=1` would repeat the playlist once, `repeat=5` would play the playlist 6 times (once, and then repeated 5 times)

**Comment by mozai** [comment]
I'm in favour of using environment values for small things (256-char string, integeters, booleans) set at start-time and only accessed once at start-time.  Instead of having two data types for "repeat", use '0' for repeat indefinitely, '1' for play once, and 'N' for repeat the playlist N times.
Should the default be '0' or '1' ?
