### ISSUE TITLE
req: skip non-media files

### ISSUE THREAD

**Issue by mozai** [wetfish/sync#14]
```
Error: /media/0000-00-00.m3u is an unsuported file type
[nodemon] app crashed - waiting for file changes before starting..
```

media folders often old non-video / non-audio files (ie. .m3u playlists, .nfo text, .jpg cover art).  You already examine each file to get stream duration, could raise a warning about incompatible files and just keep going without including them in the playlist the daemon generates at starttime.

**Comment by itsrachelfish** [comment]
This was fixed by @AngelGzS in #39
