### ISSUE TITLE
warn: Souce map error - status 404 for socket.io.js

### ISSUE THREAD

**Issue by mozai** [wetfish/sync#15]
macOS 10.13, Firefox 67.0.4

Seems to work as expected, but I have this warning in the dev condole at (client) starttime:
```
Source map error: request failed with status 404
Resource URL: http://[hostname]:3000/socket.io.js
Source Map URL: socket.io.js.map [Learn More]
```

Also seeing this in the js console repeatedly:
`removing (controls.js:12:21)`

**Comment by itsrachelfish** [comment]
@mozai I am unable to replicate this issue with the latest code in master using Firefox. Feel free to reopen if you can replicate it.
