### ISSUE TITLE
Fullscreen button

### ISSUE THREAD

**Issue by itsrachelfish** [wetfish/sync#22]
There should be a button to make the video fullscreen, right now the only way to do that is by right clicking.

**Comment by Meleeman01** [comment]
![image](https://user-images.githubusercontent.com/13123926/60926474-3328f280-a26c-11e9-809a-1f6922caafab.png)

i'm thinking we should incorporate font-awesome into the project easily, but we could also try some alternatives as well if you want to font-awesome will be easier to implement i think, I really like this font-set
![image](https://user-images.githubusercontent.com/13123926/60926720-0c1ef080-a26d-11e9-9cf5-416e27e2bb0d.png)
both of them are in npm so thats pretty cool
