### ISSUE TITLE
Use a config file instead of system environment variables

### ISSUE THREAD

**Issue by itsrachelfish** [wetfish/sync#23]
Inevitably we are going to add more configuration options and it would be nice if all of them were exposed in a single place.

There should be a gitignored config file (and a tracked config example file) for all of the options in the project, similar to an `.env` file in Laravel.

**Comment by Meleeman01** [comment]
what sort of configuration options would you like to see? maybe a custom port number?

**Comment by itsrachelfish** [comment]
This feature was added as of #39
