### ISSUE TITLE
Autoplay on firefox, otherwise display a play button

### ISSUE THREAD

**Issue by itsrachelfish** [wetfish/sync#28]
Firefox allows videos to be autoplayed with audio. When a user connects to sync with Firefox, the video should automatically start playing unmuted.

Chromium based browsers like Chrome, Opera, and Safari require user interaction before a video can be played with audio. If the user connects to sync with any browser that isn't Firefox, a big play button should be displayed that the user has to click before starting the video.

By forcing the user to click a play button first, we'd be able to always start the stream with audio enabled, instead of starting the video without audio and requiring the user to unmute.

**Comment by Meleeman01** [comment]
so i'm thinking we'll check for firefox or chrome clientside, if firefox, autoplay, unmute. else display a play button, and play/unmute the video on click.
