### ISSUE TITLE
Extend Readme

### ISSUE THREAD

**Issue by faroit** [wetfish/sync#40]
Hi, I just found this repo. From the description it looks like the idea is to 

- playback an audio file in sync to a youtube/vimeo video, eg to replace the audio stream that would be embedded in that video.

If that is the case, it would be great to add a minimum example
If thats not the case some description of what the purpose of this project is would be nice.

**Comment by itsrachelfish** [comment]
Hey there @faroit :wave: 

Currently this project just supports syncing html5 video files, but we are working on adding 3rd party video support. If you'd like to get involved we'd recommend checking out our IRC - https://wet.fish/irc

**Comment by itsrachelfish** [comment]
Readme has been updated with more detailed usage instructions.
