### ISSUE TITLE
'm' key for mute to update toolbar

### ISSUE THREAD

**Issue by mozai** [wetfish/sync#69]
Seen:
 - pressing 'm' key during playback will toggle mute
 - clicking the speaker icon will toggle mute and change the speaker icon to a cancelled-speaker icon and back

Desired:
 - pressing 'm' key will also change the speaker icon to a cancelled-speaker icon and back.

**Comment by Meleeman01** [comment]
bruh i fixed it https://github.com/wetfish/sync/pull/70
